Added new monkey patch for sublime_plugin.py for the issue
Show the Command Class name when raising `TypeError: run() missing 1 required positional argument: 'blabla'
https://github.com/SublimeTextIssues/Core/issues 2930